//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hacimehmetli.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactform
    {
        public long id { get; set; }
        public string namesurname { get; set; }
        public string gsm { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string isaktif { get; set; }
        public Nullable<System.DateTime> messagetime { get; set; }
    }
}
