//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hacimehmetli.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public long id { get; set; }
        public Nullable<long> categoryid { get; set; }
        public string urunadi { get; set; }
        public string urunphotourl { get; set; }
        public string urunaciklamasi { get; set; }
        public string urunporsiyon { get; set; }
        public Nullable<decimal> urunfiyati { get; set; }
        public string stokdurumu { get; set; }
    
        public virtual categorytable categorytable { get; set; }
    }
}
