//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hacimehmetli.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordertable
    {
        public long id { get; set; }
        public Nullable<long> productid { get; set; }
        public Nullable<long> statusid { get; set; }
        public Nullable<long> piece { get; set; }
        public string description { get; set; }
        public string adress { get; set; }
        public string gsm { get; set; }
        public string namesurname { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
    
        public virtual orderstatu orderstatu { get; set; }
        public virtual producttable producttable { get; set; }
    }
}
