//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hacimehmetli.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class producttable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producttable()
        {
            this.ordertables = new HashSet<ordertable>();
        }
    
        public long id { get; set; }
        public Nullable<long> categoryid { get; set; }
        public string productname { get; set; }
        public string productdescription { get; set; }
        public string producturl { get; set; }
        public string productphotourl { get; set; }
        public Nullable<decimal> productprice { get; set; }
        public string productporsiyon { get; set; }
        public Nullable<long> isaktif { get; set; }
        public string isitinstock { get; set; }
        public string vitrin { get; set; }
        public string topsale { get; set; }
    
        public virtual categorytable categorytable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordertable> ordertables { get; set; }
    }
}
